version: '3.8'

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.sqlite
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: alpine:latest
    volumes:
      - sqlite_data:/data
    command: tail -f /dev/null

volumes:
  sqlite_data:
